### ISSUE TITLE
fluxscale output already exists in pipeline_example execution

### ISSUE THREAD

**Issue by jmoldon** [AMIGA-IAA/hcg_hi_pipeline#5]
I was running the pipeline_example with AW234. Everything worked like a charm and the `import_data` step finished without problems. When running the rest of the pipeline it crased in the fluxscale step because `fluxsol.cal` already exists. This happen in a single execution, so I'm sure the table was not created before. The same problem happened with AW500.

This is the error in the terminal log:

```
2022-03-23 13:40:49 | INFO | Applying flux scale to calibrators (./cal_tabs/fluxsol.cal).
2022-03-23 13:40:49 | INFO | Executing command: flux_info = fluxscale(vis='AW234.ms', caltable='./cal_tabs/amp.gcal', fluxtable='./cal_tabs/fluxsol.cal', reference='0134+329', incremental=True)
2022-03-23 13:40:50	SEVERE	fluxscale::::	fluxtable ./cal_tabs/fluxsol.cal exists.
*** Error *** fluxtable ./cal_tabs/fluxsol.cal exists. Please specify a different name. Or set append=True, to append the results to the table.
2022-03-23 13:40:50	SEVERE	fluxscale::::	An error occurred running task fluxscale.
2022-03-23 13:40:49 | INFO | Writing calibrator fluxes summary to: ./summary/AW234.ms.flux.summary.
Traceback (most recent call last):
  File "/home/jmoldon/work/software/casa/casa-pipeline-release-5.6.2-2.el7/lib/python2.7/init_welcome.py", line 33, in <module>
    execfile(__candidates[0])
  File "./flag_calib_split.py", line 1231, in <module>
    calibration(msfile,config,config_raw,logger)
  File "./flag_calib_split.py", line 894, in calibration
    for k in range(len(flux_info.keys())):
AttributeError: 'NoneType' object has no attribute 'keys'
# 2022-03-23 14:40:50,172 INFO {"task": "'flag_calib_split'", "task_status": "update", "task_total": 1, "task_completed": 0, "task_completed_percent": 0.0}
```
Looking at the casa log I confirm that the fluxscale step was executed twice:

```
2022-03-23 13:40:22 INFO    fluxscale::::+  ##### Begin Task: fluxscale          #####
2022-03-23 13:40:22 INFO    fluxscale::::   fluxscale(vis="AW234.ms",caltable="./cal_tabs/amp.gcal",fluxtable="./cal_tabs/fluxsol.cal",reference="0134+329",transfer=[''],
2022-03-23 13:40:22 INFO    fluxscale::::+          listfile="",append=False,refspwmap=[-1],gainthreshold=-1.0,antenna="",
2022-03-23 13:40:22 INFO    fluxscale::::+          timerange="",scan="",incremental=True,fitorder=1,display=False)
```

and then 

```
2022-03-23 13:40:50 INFO    fluxscale::::+  ##### Begin Task: fluxscale          #####
2022-03-23 13:40:50 INFO    fluxscale::::   fluxscale(vis="AW234.ms",caltable="./cal_tabs/amp.gcal",fluxtable="./cal_tabs/fluxsol.cal",reference="0134+329",transfer=[''],
2022-03-23 13:40:50 INFO    fluxscale::::+          listfile="",append=False,refspwmap=[-1],gainthreshold=-1.0,antenna="",
2022-03-23 13:40:50 INFO    fluxscale::::+          timerange="",scan="",incremental=True,fitorder=1,display=False)
```
I have not followed the logic of why this happens, but I attach here the pipeline log and the casa log for the AW500 execution.

[pipeline.log](https://github.com/AMIGA-IAA/hcg_hi_pipeline/files/8333580/pipeline.log)
[casa-20220323-134803.log](https://github.com/AMIGA-IAA/hcg_hi_pipeline/files/8333583/casa-20220323-134803.log)

**Comment by jonesmg** [comment]
Thanks for finding this issue. Can you send me the AW234.log and AW500.log files please? These are probably the most important to see what's happening. 

The pipeline is meant to run the calibration step twice. The rflag algorithm is only meant to be used after an initial calibration, so it does the initial flagging (manual + tfcrop) then calibrates, then runs rflag, then repeats the calibration with the final flags. However, I'm not sure why it is crashing. Perhaps this is something that changed from CASA 5.4 to 5.6. I'll see what the logs say when you send them and if I can't figure it out them I'll try to reproduce the error on my end.

**Comment by jmoldon** [comment]
Sure:
[AW500.log](https://github.com/AMIGA-IAA/hcg_hi_pipeline/files/8335268/AW500.log)
[AW234.log](https://github.com/AMIGA-IAA/hcg_hi_pipeline/files/8335270/AW234.log)

I don't think it is related to the CASA version, because the problem is that the fluxscale is executed a second time, and the fluxsol table already exists, maybe an "overwrite" option is different between the two versions, but I doubt it.

**Comment by jonesmg** [comment]
I checked in the CASA docs and unfortunately the documentation is incomplete for 5.6, but in 5.4 the default option is to overwrite the existing flux scale table, but in 6.1 if the table already exists it will cause an error. So I suspect the changed in 5.6, but it's not fully documented. I'll try to reproduce the error when I have time and will see if there is a simple solution that will work for both 5.4 and 5.6.

**Comment by jmoldon** [comment]
Yes, I think it could be probably be that:

In CASA 5.4.0-68:
```
append -- Append fluxscaled solutions to the fluxtable.
        default: False; (will overwrite if already existing)
        example: append=True

```
In CASA  5.6.2-2
```
      append: Append fluxscaled solutions to the fluxtable?
 |                           Default: False (the fluxtable must not exist)
 |                           Options: False|True
 |      
 |                         Default
 Value: False
```

I don't have both in the same computer, so I could not actually test both with these data. 

Either way, the solutions could be: to add a step that checks for existance and removes it if it exists, or that you say explicitly in the README that the pipeline only works with 5.4 (I think it says it probably should work with all 5.X versions).

**Comment by jonesmg** [comment]
Ok. I've tried to make a quick fix that deletes any existing flux solution table before running fluxscale. Can you pull the CASA5.6_fix branch to test it? https://github.com/AMIGA-IAA/hcg_hi_pipeline/tree/CASA5.6_fix
